DISTRO=ubuntu20.04
CUDA_VER=11.4.3
CUDNN_VER=8
PYTHON_VER=3.11
TAG=cuda${CUDA_VER}_cudnn${CUDNN_VER}_py${PYTHON_VER}

RUN_USER=developer
RUN_GROUP=developer
RUN_UID=1000
RUN_GID=1000
PROJECT=fastapi_template
BASENAME=$(whoami)/$PROJECT
DISPLAY=:0.0
